config/routes.rb
Tutor::Application.routes.draw do
	
	ActiveAdmin.routes(self)
	devise_for :admin_users, ActiveAdmin::Devise.config
	devise_for :teaching_assistants
	devise_for :students
	devise_for :lecturers

	get 'courses/sign_up'
	get 'courses/find_course/:id' => 'courses#find_course'
	get 'tracks/show_classmates/:id' => 'tracks#show_classmates'
	get 'solutions/mark_solution'
	get 'solutions/view_submissions'
	post 'solutions/compile_solution' => 'solutions#compile_solution'
	post 'courses/new' => 'courses#new'
	post 'courses/share' => 'courses#share'
	post 'solutions/execute' => 'solutions#execute'
	post '/posts/:id' => 'posts#update'
	post 'tracks/insert_recommendation' => 'tracks#insert_recommendation'
	post 'debuggers/:id' => 'debuggers#start'
	post 'cproblems/submit' => 'cproblems#submit'
	get 'contests/add_problems/:id' => 'contests#add_problems'
	get 'contests/:id/standings' => 'contests#standings'
	get 'contests/:id/registrants' => 'contests#registrants'
	get 'contests/:id/register' => 'contests#register'
	post 'contests/add/:id' => 'contests#add'
	get 'problems/edit'
	get '/courses/return_list' => 'courses#return_list'
	get 'c_problems/new'
	post 'c_problems/create'
	post '/courses/register' => 'courses#register'

	get "tips/new"
	get "tips/create"
	get "tips/show"
	get "tips/index"
	get "tips/edit"
	get "tips/destroy"
	post "tips/:id/edit" => 'tips#update'
	get "problems/destroy"
	get "test_cases/edit"
	get "test_cases/destroy"
	get "model_answers/edit"
	get "hints/edit"
	get "model_answers/destroy"
	get "model_answers/back"
	get "notes/destroy"
	get "grades/view_grades"

	root 'site#index'
	resources :tracks do
		post 'getProblems', on: :member
	end
	resources :assignment_testcases
	resources :problems_by_tas
	resources :solutions
	resources :problems
	resources :courses
	resources :cproblems
	resources :contests
	resources :contributors

	post "courses/choose"
	post "courses/existing"
	post "courses/duplicate"
	get "model_answers/new"
	post "model_answers/new"

	resources :model_answers

	resources :discussion_boards do
		post 'toggle', on: :member
	end
	post 'courses/new' => 'courses#new'
	resources :courses do
		post 'topics/new' => 'topics#new'
		resources :topics
	end
	resources :model_answers do
		post "model_answers/new"
	end

	resources :assignments do
		get "assignments/new"
		post "assignments/show"
		get "assignments/show"
	end
	resources :assignments_problems do
		get "assignment_problems/new"
		get "assignment_problems/edit"
		get "assignment_problems/show"
		get "assignment_problems/index"
		post "assignment_problems/update"
		post "assignment_problems/show"
	end
	post "/assignment_problems/complete"
	resources :assignments_testcases do
		get "assignment_testcases/new"
		get "assignment_testcases/show"
		get "assignment_testcases/index"
		get "assignment_testcases/edit"
		get "/assignment_testcases/new"
	end

	resources :courses do
		post 'hide', on: :member
	end
	resources :test_cases

	resources :courses
	resources :test_cases
	resources :model_answers
	resources :solutions
	resources :topics
	resources :replies
	resources :hints
	resources :lecturers
	resources :teaching_assistants
	resources :students
	resources :posts
	resources :facebook
	resources :tips
	resources :notifications
	resources :contests
	resources :assignments
	resources :assignment_problems
	resources :notes
	resources :grades

	resources :tracks do
		member do
			get 'getProblems'
		end
	end

	resources :courses do
		member do
			get 'show_grades'
		end
	end

	resources :assignments do
		member do
			get 'show_correction'
		end
	end

	resources :courses do
		collection do
			post 'sort'
		end
	end

	resources :topics do
		collection do           
			post 'sort'
		end
	end

	resources :discussion_boards do
		member do
			post 'toggle'
		end
	end
	
	resources :model_answers do
		post "model_answers/new"
	end

	resources :tips do
		 get "tips/index"
	end

	resources :hints do
		 get "hints/index"
	end

	resources :solutions_constraints do
		collection do
			post "new"
		end
	end

	resources :problems do
		get 'done'
		get 'destroy_problem'
	end

	resources :courses do
		post 'topics/new' => 'topics#new'
		resources :topics
		resources :teaching_assistants
		post 'teaching_assistants/new' => 'teaching_assistants#new'
		resources :acknowledgements
		resources :resources, only: [:create, :index, :new, :destroy] do
			get :add_more, on: :collection
		end
	end

	get "utilities/simple_search"
	get "utilities/advanced_search"
	get "utilities/auto_complete"

    match ":controller(/:action(/:id))", :via => :get
end

app/models/contest.rb
class Contest < ActiveRecord::Base

	#Validations
	validates :title, presence: true
	validate :duplicate_title, :on => :create
	validate :validate_start_date_before_end_date
	validate :validate_future_start_time

	#Relations
	belongs_to :owner, polymorphic: true
	belongs_to :course

	has_many :progress, class_name: 'ContestProgress'
	has_and_belongs_to_many :students, class_name:"Student", join_table: "contests_students"
	has_and_belongs_to_many :problems, class_name:"Cproblem", join_table: "contests_cproblems"

	#Scoops

	#Methods

	# [Contest Standings - Story 5.25]
	# Sorts students in contest according to the number of correct problems
	# 	they solved and the total time of submission
	# Parameters: none
	# Returns: Sorted Hash containing ContestProgress of students
	# Author: Mohab Ghanim
	def get_contest_standings
		contest_standing_records = ContestProgress.where(contest_id: self.id)
		contest_standings_unique = Hash.new
		contest_standing_records.each do |record|
			wrong_answers = ContestProgress.where(contest_id: self.id,
				student_id: record.student.id,
				status: false).count
			time_spent = 0
			ContestProgress.where(contest_id: self.id,
				student_id: record.student.id).each do |progress|
				updated_at = ContestProgress.where(contest_id: self.id, cproblem_id:
					progress.cproblem_id, student_id: record.student.id).take.updated_at
				start_time = Contest.find(self.id).start_time
				time_spent = time_spent + ((updated_at - start_time)/60).to_i
			end
			contest_standings_unique[record.student_id] = {wrong_answers: wrong_answers,
				record: record, time_spent: time_spent}
		end
		return Hash[contest_standings_unique.sort_by {|key, value| [value[:wrong_answers],
			value[:time_spent]]}.to_a]
	end

	# [Create Contest - Story 5.16]
	# Validates that the contest end date/time is after its
	# 	start date/time
	# Parameters: none
	# Returns: none
	# Author: Amir George
	def validate_start_date_before_end_date
		if end_time <= start_time
			errors.add(:end_time, "must be after start time")
		end
	end

	# [Create Contest - Story 5.16]
	# Validates that no contest with the same title exists
	# Parameters: none
	# Returns: none
	# Author: Amir George
	def duplicate_title
		if Contest.find_by title: title
			errors.add(:title, "has already been taken")
		end
	end

	# [Create Contest - Story 5.16]
	# Validates that contest's start time must be in the future
	# Parameters: none
	# Returns: none
	# Author: Amir George
	def validate_future_start_time
		if start_time <= Time.now
			errors.add(:start_time, "must be in the future")
		end
	end

end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController

	before_action :validate_timer, only: [:standings, :show, :registrants]

	# [Contest Standings - Story 5.25]
	# Returns the contest object whose id is params[:id]
	# Parameters: none
	# Returns: none
	# Author: Mohab Ghanim
	def standings
		@contest = Contest.find_by_id(params[:id])
	end

	# [Contest Registration - Story 5.24]
	# Add the current student to the choosen contest
	# Parameters:
	# 	params[:id]: The current contest id
	# Returns: none
	# Author: Rania Abdel Fattah
	def register
		if student_signed_in?
			contest = Contest.find_by_id(params[:id])
			current_student.contests << contest
			redirect_to "/contests"
		end
	end

	# [Edit Contest - Story 5.17]
	# Passes instance variable of the contest to be edited to the edit
	# 	view and renders the edit view
	# Parameters: none
	# Returns: none
	# Author: Amir George
	def edit
		if student_signed_in?
			render ('public/404')
		end
		@contest = Contest.find(params[:id])
		if lecturer_signed_in? &&
			!current_lecturer.contests.include?(@contest)
			render ('public/404')
		elsif teaching_assistant_signed_in? &&
			!current_teaching_assistant.contests.include?(@contest)
			render ('public/404')
		end
	end

	# [View Contest Problems - Story 5.26]
	# Description: Displays the contest that the user chose
	# Parameters:
	#	@contest: The contest id that the user chose
	#	@problems = The list of problems of the contest
	# Returns: The view of the contest
	# Author: Ahmed Atef
	def show
		@contest = Contest.find(params[:id])
		@problems =  @contest.problems.all
	end

	# [View Contests - Stroy 5.19]
	# This action renders a list of all contests belonging to 
	#	the current user.
	# Parameters:
	#	current_lecturer: The current signed in lecturer
	#	current_teaching_assistant: The currrent signed in teaching assistant
	#	current_students: The current signed in student	
	# Returns: 
	#	@contest: A list of all the user's contests
	# Author: Muhammad Mamdouh
	def index
		if current_lecturer
			@contests = current_lecturer.contests
		elsif current_teaching_assistant
			@contests = current_teaching_assistant.contests
		elsif current_student
			@my_contests = current_student.contests
			@courses = current_student.courses
			@contests = []
			@courses.includes(:contests).each do |course|
				course.contests.each do |contest|
					unless @my_contests.exists?(contest.id)
						@contests << contest
					end
				end
			end
		end
	end	

	# [Create Contest - Story 5.16]
	# Defines a new Contest instance for the form in the new view
	# Parameters: none
	# Returns: none
	# Author: Amir George
	def new
		if student_signed_in?
			render ('public/404')
		end
		if(@new_contest == nil)
			@new_contest = Contest.new
		end
	end

	# [Edit Contest - Story 5.17]
	# Takes the updated values from the view form and updates record
	# 	in database accordingly
	# Parameters: none
	# Returns: none
	# Author: Amir George
	def update
		@contest  = Contest.find(params[:id])
		@contest.course = Course.find_by_name(course_param[:course])
		if @contest.update_attributes(contest_params_update)
			redirect_to(:action => 'show', :id => @contest.id)
		else
			render :action=>'edit'
		end
	end

	# [Create Contest - Story 5.16]
	# Takes the params submitted from new form and inserts record
	# Parameters: none
	# Returns: none
	# Author: Amir George
	def create
		if student_signed_in?
			render ('public/404')
		end
		@new_contest  = Contest.new
		@new_contest.title = contest_params[:title]
		unless contest_params[:course] == ""
			@new_contest.course = Course.find_by_name(contest_params[:course])
		end
		@new_contest.description = contest_params[:description]
		@new_contest.start_time = DateTime.new(
			contest_params["start_time(1i)"].to_i,
			contest_params["start_time(2i)"].to_i,
			contest_params["start_time(3i)"].to_i,
			contest_params["start_time(4i)"].to_i,
			contest_params["start_time(5i)"].to_i)
		@new_contest.end_time = DateTime.new(
			contest_params["end_time(1i)"].to_i,
			contest_params["end_time(2i)"].to_i,
			contest_params["end_time(3i)"].to_i,
			contest_params["end_time(4i)"].to_i,
			contest_params["end_time(5i)"].to_i)
		if lecturer_signed_in?
			@new_contest.owner = current_lecturer
		elsif teaching_assistant_signed_in?
			@new_contest.owner = current_teaching_assistant
		end

		if @new_contest.save
			flash[:success_creation]= "Contest added."
			Notification.contests_notify(@new_contest.course_id,
				@new_contest.id)
			redirect_to :action => 'index'
		else
			render :action=>'new'
		end
	end

	# [Add Contest Problem - Story 5.18]
	# Passes instance variable of the contest to the add
	# 	problems view and renders the add problems view
	# Parameters: none
	# Returns: none
	# Author: Amir George
	def add_problems
		if student_signed_in?
			render ('public/404')
		end
		@contest = Contest.find(params[:id])
		if lecturer_signed_in?  &&
			!current_lecturer.contests.include?(@contest)
			render ('public/404')
		elsif teaching_assistant_signed_in? &&
			!current_teaching_assistant.contests.include?(@contest)
			render ('public/404')
		end
		@problems = Cproblem.all
		courseContests = @contest.course.contests
		courseContests.includes(:problems).each do |contest|
			@problems = @problems - contest.problems
		end
	end

	# [Add Contest Problem - Story 5.18]
	# Adds a certain problem to the contest if it was not
	# 	added before
	# Parameters: none
	# Returns: none
	# Author: Amir George
	def add
		@contest = Contest.find(params[:id])
		@problem = Cproblem.find(params[:problem_id])
		if @contest.problems.find_by_id(@problem.id).nil?
			@contest.problems << @problem
		end
		flash[:added] = "Your Problem is now added"
		redirect_to :back
	end

	# [Edit Contest - Story 5.17]
	# Gets the course id, removes it from the database and then
	# 	redirects the user to the show contests page
	# Parameters: none
	# Returns: none
	# Author: Amir George
	def destroy
		if student_signed_in?
			render ('public/404')
		end
		contest = Contest.find(params[:id])
		if lecturer_signed_in? &&
			!current_lecturer.contests.include?(contest)
			render ('public/404')
		elsif teaching_assistant_signed_in? &&
			!current_teaching_assistant.contests.include?(contest)
			render ('public/404')
		else
		contest.destroy
		flash[:success_deletion] = "Contest deleted."
		redirect_to :action => 'index'
		end
	end

	def registrants
		@contest_registrants = Contest.find_by_id(params[:id]).students
	end

	# [Create Contest - Story 5.16]
	# Defines contest parameters to be permitted from the form view
	private
		def contest_params
			params.require(:contest).permit(:title, :description,
				:course, :start_time, :end_time)
		end

	# [Edit Contest - Story 5.17]
	# Defines the parameters for the contest to be permitted from the
	# 	form view
	private
		def contest_params_update 
			params.require(:contest).permit(:title, :description,
				:start_time, :end_time)
		end

	# [Edit Contest - Story 5.17]
	# Permits the course parameter from the view to be handled separately
	# 	in the update action
	# Parameters: none
	# Returns: none
	# Author: Amir George
	private
		def course_param
			params.require(:contest).permit(:course)
		end

	# [Contest Timer - Story 5.28]
	# Checks the state of the timer based on the date and time of a specific contest
	# 	and affecting the behaviour of the timer and the message that accompanies it
	# 	based on the timing of the contest. If the contest didn't start yet, the timer
	# 	will be set to countdown till the start of the contest and the message appearing
	# 	will be 'Contest starts in'. If the contest has started, the timer will be set
	# 	to countdown till the end of the contest and the message will be 'Contest ends in'.
	# 	If the contest has ended, the timer will disappear and the message will be
	# 	'Contest has finished!'.
	# Parameters:
	# 	params[:id]: an Integer containing the id of a specific contest to have its timer.
	# Returns:
	# 	@timer: a String representation of a DateTime object representing the date
	# 		and the time of the contest that will be used by the timer.
	# 	@message: a String containing the message accompanying the timer.
	# 	@del: a Boolean indicating if the contest has finished which affects the
	# 		behaviour of the timer; whether to remove it or not.
	# Author: Khaled Helmy
	private
		def validate_timer
			@contest = Contest.find(params[:id])
			contest_start = @contest.start_time
			contest_end = @contest.end_time
			current = DateTime.now
			if current < contest_start
				@timer = contest_start
				@message = "Contest starts in"
				@del = false
			elsif current <= contest_end
				@timer = contest_end
				@message = "Contest ends in"
				@del = false
			else
				@timer = nil
				@message = "Contest has finished!"
				@del = true
			end
		end

end

app/helpers/contest_helper.rb
module ContestHelper
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_show_timer.html.erb
<%= javascript_include_tag "contests" %>

<center>
	<%= content_tag "div", id: "temp", data: {timer: @timer, del: @del} do %>
	<% end %>
	<h4><%= @message %></h4>
	<div id="countdown" />
</center>

app/views/contests/add_problems.html.erb
<div class='left-row'>
	<div class="container" style="width:100%">
		<div class="page-header">
			<h1>
				Add problems
			</h1>
		</div>
		<% openable = true %>
		<div class="panel-group list-group" id="accordion">
			<% if flash[:added] %>
				<%= flash[:added] %>
			<% end %>
			<% if @problems.size == 0 %>
				<br>
				There are no problems to add.
			<% end %>
			<% @problems.each do |problem| %>
				<% color = "label label-success" %>
				<% if openable %>
					<% open = "in" %>
					<% openarrow = "glyphicon-chevron-down" %>
					<% openable = false %>
				<% else %>
					<% open = "" %>
					<% openarrow = "glyphicon-chevron-right" %>
				<% end %>
				<div class="panel panel-default">
					<div class="panel-title list-group-item list-group-item-info">
						<a class="icon glyphicon <%= openarrow %>"
							href="#<%= problem.id.to_s %>"
							data-toggle="collapse" data-parent="#accordion"
							style="margin-right: 1%; text-decoration: none;">
						</a>
						<%= problem.title %>
					</div>
					<div id="<%= problem.id.to_s %>" class="panel-collapse collapse <%= open %>">
						<%= problem.description %>
						<%= link_to "Add", {:action => 'add', :problem_id => problem.id,
							:id => @contest.id }, class: 'btn btn-info', method: 'post' %>
					</div>
				</div>
			<% end %>
		</div>
		<%= link_to "Back to edit page", {:action => 'edit', :id => @contest.id}, class: "btn btn-success" %>
	</div>
</div>

app/views/contests/edit.html.erb
<div class="left-row" style="padding:10px 10px 10px 10px;">
	<div class="container" style="width:100%">
		<div>
			<h1>Update Contest Info</h1>
			<%= form_for :contest, url: contest_path(@contest), method: :patch do |f| %>
				<p>
					<%= f.label :Title %><br>
					<% unless @contest.errors[:title].blank? %>
						<span id="error_explanation">
							Title <%= @contest.errors[:title].join(", ") %>
						</span>
						<br>
					<% end %>
					<%= f.text_field :title, :value => @contest.title,
						class: "form-control", style: "width:300px",
							placeholder: "Title" %>
				</p>
				<p>
					<%= f.label :Start_Time %><br />
					<% unless @contest.errors[:start_time].blank? %>
						<span id="error_explanation">
							Start Time <%= @contest.errors[:start_time].join(", ") %>
						</span>
						<br>
					<% end %>
					<%= f.datetime_select :start_time, {:start_year => Date.today.year + 1,
						:end_year => Date.today.year, :value => @contest.start_time} %>
				</p>
				<p>
					<%= f.label :End_Time %><br />
					<% unless @contest.errors[:end_time].blank? %>
						<span id="error_explanation">
							End Time <%= @contest.errors[:end_time].join(", ") %>
						</span>
						<br>
					<% end %>
					<%= f.datetime_select :end_time, {:start_year => Date.today.year + 1,
						:end_year => Date.today.year, :value => @contest.end_time} %>
				</p>
				<p>
					<% if lecturer_signed_in? %>
						<% @owner_courses = current_lecturer.courses %>
						<% @owner_courses = @owner_courses.map {|x| x.name} %>
					<% elsif teaching_assistant_signed_in? %>
						<% @owner_courses = current_teaching_assistant.courses %>
						<% @owner_courses = @owner_courses.map {|x| x.name} %>
					<% end %>
					<%= f.label :Course %><br>
					<% unless @contest.errors[:course].blank? %>
						<span id="error_explanation">
							Course <%= @contest.errors[:course].join(", ") %>
						</span>
						<br>
					<% end %>
					<%= f.collection_select :course, @owner_courses, :to_s, :to_s,
					:include_blank => false %>
				</p>
				<p>
					<%= f.label :Description %><br>
					<% unless @contest.errors[:description].blank? %>
						<span id="error_explanation">
							Description <%= @contest.errors[:description].join(", ") %>
						</span>
						<br>
					<% end %>
					<%= f.text_area :description, class: "form-control",
					style: "width:300px", placeholder: "Description",
					:value => @contest.description %>
				</p>
				<p>
					<% if true %>
					<center><%= link_to "Add problems", {:action => 'add_problems',
						:id => @contest.id}, class: "btn btn-success" %></center>
					<br />
					<% end %>
				</p>
				<p>
					<center><%= f.submit "Update contest", class: "btn btn-info" %></center>
				</p>
			<% end %>
		</div>
	</div>
</div>

app/views/contests/index.html.erb
<div class="left-row" style="padding:10px 10px 10px 10px;">
	<% if @my_contests != nil %>
		<h1> Your Contests </h1>
		<table class="table table-striped table-bordered table-responsive">
			<tr>
				<td>Contest title</td>
				<td>Start time</td>
				<td>Duration</td>
			</tr>
			<% if @my_contests.size !=0 %>
			<% @my_contests.each do |contest| %>
				<tr>
					<td>
						<h4><%= link_to contest.title, :controller => 'contests', :action=> 'show',
								:id => contest.id %></h4>
					</td>
					<td>
						<h4><%= contest.start_time %></h4>
					</td>
					<td>
						<h4><%=((contest.end_time - contest.start_time)/(60*60)).to_i %> hours</h4>
					</td>
				</tr>
			<% end %>
			<% end %>
		</table>	
	<% end %>	
	<h1> Contests </h1>
	<hr>
	<table class="table table-striped table-bordered table-responsive">
		<% if @contests.size != 0 %>
			<tr>
				<td>Contest title</td>
				<td>Start time</td>
				<td>Duration</td>
				<td>Actions</td>
			</tr>
			<% @contests.each do |contest| %>
				<tr>
					<td>
						<h4><%= link_to contest.title, :controller => 'contests', :action=> 'show',
								:id => contest.id %>
						</h4>
					</td>
					<td>
						<h4><%= contest.start_time %></h4>
					</td>
					<td>
						<h4><%= ((contest.end_time - contest.start_time)/(60*60)).to_i %> hours</h4>
					</td>
					<% if current_lecturer || current_teaching_assistant %>
						<td>
							<h4><%= link_to "Edit", "/contests/#{contest.id}/edit" %></h4>
						</td>
					<% elsif contest.end_time < DateTime.now %>
						<td>
							<h4> Contest finished </h4>
						</td>
					<% else %>	
						<td>
							<h4><%= link_to "Register",
							"/contests/#{contest.id}/register" %></h4>
						</td>
					<% end %>					
				</tr>
			<% end %>
		<% else %>
			You have no contests
		<% end %>	
	</table>
	<% if current_lecturer || current_teaching_assistant %>
		<center><%= button_to "Create new contest", {action: "new"}, 
			:class => "btn btn-info", :method => :get %></center>
	<% end %>
</div>

app/views/contests/new.html.erb
<div class="left-row" style="padding:10px 10px 10px 10px;">
	<h1>Create New Contest</h1>
	<hr>
	<%= form_for :contest, url: contests_path do |f| %>
		<p>
			<%= f.label :Title %><br>
			<% unless @new_contest.errors[:title].blank? %>
				<span id="error_explanation">
					Title <%= @new_contest.errors[:title].join(", ") %>
				</span>
				<br>
			<% end %>
			<%= f.text_field :title, :value => @new_contest.title,
			class: "form-control", style: "width: 300px", placeholder: "Title" %>
		</p>
		<p>
			<%= f.label :Start_Time %><br />
			<% unless @new_contest.errors[:start_time].blank? %>
				<span id="error_explanation">
					Start Time <%= @new_contest.errors[:start_time].join(", ") %>
				</span>
				<br>
			<% end %>
			<%= f.datetime_select :start_time, {:start_year => Date.today.year + 1,
				:end_year => Date.today.year, :value => Time.now} %>
		</p>
		<p>
			<%= f.label :End_Time %><br />
			<% unless @new_contest.errors[:end_time].blank? %>
				<span id="error_explanation">
					End Time <%= @new_contest.errors[:end_time].join(", ") %>
				</span>
				<br>
			<% end %>
			<%= f.datetime_select :end_time, {:start_year => Date.today.year+1,
				:end_year => Date.today.year, :value => Time.now} %>
		</p>
		<p>
			<% if lecturer_signed_in? %>
				<% @owner_courses = current_lecturer.courses %>
				<% @owner_courses = @owner_courses.map {|x| x.name} %>
			<% elsif teaching_assistant_signed_in? %>
				<% @owner_courses = current_teaching_assistant.courses %>
				<% @owner_courses = @owner_courses.map {|x| x.name} %>
			<% end %>
			<%= f.label :Course %><br>
			<% unless @new_contest.errors[:course].blank? %>
				<span id="error_explanation">
					Course <%= @new_contest.errors[:course].join(", ") %>
				</span>
				<br>
			<% end %>
			<%= f.collection_select :course, @owner_courses, :to_s, :to_s,
				:include_blank => false %>
		</p>
		<p>
			<%= f.label :Description %><br>
			<% unless @new_contest.errors[:description].blank? %>
				<span id="error_explanation">
					Description <%= @new_contest.errors[:description].join(", ") %>
				</span>
				<br>
			<% end %>
			<%= f.text_area :description, class: "form-control", style: "width: 300px",
				placeholder: "Description", :value => @new_contest.description %>
		</p>
		<p>
			<%= f.submit "Save", class: "btn btn-info" %>
		</p>
	<% end %>
</div>

app/views/contests/registrants.html.erb
<div class="left-row">
	<div class="container" style='width:100%'>
		<%= render "contests/show_timer" %><br />
		<div class="contest_information">
			<ul>
				<li><a href ="/contests/<%= @contest.id %>/">Problems</a></li>
				<li><a href ="/contests/<%= @contest.id %>/standings">Standings</a></li>
			</ul>
		</div>
		<h4>Contest Name:-</h4> <%= Contest.find_by_id(2).title %>
		<h4> Registrants:-</h4>
		<% @contest_registrants.each do |registrant| %>
			<li><%= registrant.name %></li>
		<% end %>
	</div>
</div>

app/views/contests/show.html.erb
<!--  Name: The Show contest view 
    Author: Ahmed Atef
-->
<div class='left-row'>
	<div class="container" style='width:100%'>
		<%= render "contests/show_timer" %>
		<table class="table table-striped table-bordered table-responsive">
			<div align="center">
				<h3><%= @contest.title %></h3>	
			</div>
			<% if @contest.start_time == nil || @contest.start_time > DateTime.now %>
				<center><h1> The Contest hasn't started yet <h1></center>
			<% else %>
				<div class="contest_information">
					<ul>
						<li><a href ="/contests/<%= @contest.id %>/standings">Standings</a></li>
						<li><a href ="/contests/<%= @contest.id %>/registrants">Registrants</a></li>
					</ul>
				</div>
				<% unless @problems.blank? %>
					<tr>
						<td>Problem Number</td>
						<td>Title</td>
						<td>Time limit</td>
					</tr>
					<% counter = 1 %>
					<% @problems.each do |problem| %>
						<tr>
							<td>
								<%= counter %> <br/>
								<% counter = counter + 1 %>
							</td>
							<td> 
								<%= link_to problem.title,:controller =>'cproblems',:action =>'show',
									:contest_id => @contest.id %><br/>
							</td>
							<td>
								<%= problem.time_limit %><br/>
							</td>
						</tr>
					<% end %>
				<% else %>
					No Problems yet in this contest
				<% end %>
			<% end %>	
		</table>
	</div>
</div>