config/routes.rb
Tutor::Application.routes.draw do
	
	ActiveAdmin.routes(self)
	devise_for :admin_users, ActiveAdmin::Devise.config
	devise_for :teaching_assistants
	devise_for :students
	devise_for :lecturers

	get 'courses/sign_up'
	get 'courses/find_course/:id' => 'courses#find_course'
	get 'tracks/show_classmates/:id' => 'tracks#show_classmates'
	get 'solutions/mark_solution'
	get 'solutions/view_submissions'
	post 'solutions/compile_solution' => 'solutions#compile_solution'
	post 'courses/new' => 'courses#new'
	post 'courses/share' => 'courses#share'
	post 'solutions/execute' => 'solutions#execute'
	post '/posts/:id' => 'posts#update'
	post 'tracks/insert_recommendation' => 'tracks#insert_recommendation'
	post 'debuggers/:id' => 'debuggers#start'
	post 'cproblems/submit' => 'cproblems#submit'
	get 'contests/add_problems/:id' => 'contests#add_problems'
	get 'contests/:id/standings' => 'contests#standings'
	get 'contests/:id/registrants' => 'contests#registrants'
	get 'contests/:id/register' => 'contests#register'
	post 'contests/add/:id' => 'contests#add'
	get 'problems/edit'
	get '/courses/return_list' => 'courses#return_list'
	get 'c_problems/new'
	post 'c_problems/create'
	post '/courses/register' => 'courses#register'

	get "tips/new"
	get "tips/create"
	get "tips/show"
	get "tips/index"
	get "tips/edit"
	get "tips/destroy"
	post "tips/:id/edit" => 'tips#update'
	get "problems/destroy"
	get "test_cases/edit"
	get "test_cases/destroy"
	get "model_answers/edit"
	get "hints/edit"
	get "model_answers/destroy"
	get "model_answers/back"
	get "notes/destroy"
	get "grades/view_grades"

	root 'site#index'
	resources :tracks do
		post 'getProblems', on: :member
	end
	resources :assignment_testcases
	resources :problems_by_tas
	resources :solutions
	resources :problems
	resources :courses
	resources :cproblems
	resources :contests
	resources :contributors

	post "courses/choose"
	post "courses/existing"
	post "courses/duplicate"
	get "model_answers/new"
	post "model_answers/new"

	resources :model_answers

	resources :discussion_boards do
		post 'toggle', on: :member
	end
	post 'courses/new' => 'courses#new'
	resources :courses do
		post 'topics/new' => 'topics#new'
		resources :topics
	end
	resources :model_answers do
		post "model_answers/new"
	end

	resources :assignments do
		get "assignments/new"
		post "assignments/show"
		get "assignments/show"
	end
	resources :assignments_problems do
		get "assignment_problems/new"
		get "assignment_problems/edit"
		get "assignment_problems/show"
		get "assignment_problems/index"
		post "assignment_problems/update"
		post "assignment_problems/show"
	end
	post "/assignment_problems/complete"
	resources :assignments_testcases do
		get "assignment_testcases/new"
		get "assignment_testcases/show"
		get "assignment_testcases/index"
		get "assignment_testcases/edit"
		get "/assignment_testcases/new"
	end

	resources :courses do
		post 'hide', on: :member
	end
	resources :test_cases

	resources :courses
	resources :test_cases
	resources :model_answers
	resources :solutions
	resources :topics
	resources :replies
	resources :hints
	resources :lecturers
	resources :teaching_assistants
	resources :students
	resources :posts
	resources :facebook
	resources :tips
	resources :notifications
	resources :contests
	resources :assignments
	resources :assignment_problems
	resources :notes
	resources :grades

	resources :tracks do
		member do
			get 'getProblems'
		end
	end

	resources :courses do
		member do
			get 'show_grades'
		end
	end

	resources :assignments do
		member do
			get 'show_correction'
		end
	end

	resources :courses do
		collection do
			post 'sort'
		end
	end

	resources :topics do
		collection do           
			post 'sort'
		end
	end

	resources :discussion_boards do
		member do
			post 'toggle'
		end
	end
	
	resources :model_answers do
		post "model_answers/new"
	end

	resources :tips do
		 get "tips/index"
	end

	resources :hints do
		 get "hints/index"
	end

	resources :solutions_constraints do
		collection do
			post "new"
		end
	end

	resources :problems do
		get 'done'
		get 'destroy_problem'
	end

	resources :courses do
		post 'topics/new' => 'topics#new'
		resources :topics
		resources :teaching_assistants
		post 'teaching_assistants/new' => 'teaching_assistants#new'
		resources :acknowledgements
		resources :resources, only: [:create, :index, :new, :destroy] do
			get :add_more, on: :collection
		end
	end

	get "utilities/simple_search"
	get "utilities/advanced_search"
	get "utilities/auto_complete"

    match ":controller(/:action(/:id))", :via => :get
end

app/models/hint.rb
class Hint < ActiveRecord::Base

	#Validations
	validates :message, presence: true
	validates :time, presence: true,
		numericality: {only_integer: true, greater_than_or_equal_to: 0,
		message: "must be an integer & greater than or equal to 0"}
	validates_uniqueness_of :message, :scope => :model_answer_id 
	validates :submission_counter, presence: true,
		numericality: {only_integer: true, greater_than_or_equal_to: 0,
		message: "must be an integer & greater than or equal to 0"}

	#Relations
	belongs_to :model_answer
	belongs_to :owner, polymorphic: true

	#Methods
	# [Add/Edit wizard - Story 1.28 ]
	# Description:
	#	find all hints related to a specific model answer
	# Parameters:
	#	model_answer_id: model answer hints related to.
	# Returns:
	#	Array of hints
	# Author: Ahmed Osam
	def self.get_hints model_answer_id
		Hint.find(:all, :conditions => ["category = ? AND model_answer_id = ?",
			false, model_answer_id])
	end

	# [Add/Edit wizard - Story 1.28 ]
	# Description:
	#	find all hints related to a specific model answer
	# Parameters:
	#	model_answer_id: model answer tips related to.
	# Returns:
	#	Array of tips
	# Author: Ahmed Osam
	def self.get_tips model_answer_id
		Hint.find(:all, :conditions => ["category = ? AND model_answer_id = ?",
			true, model_answer_id])
	end
end

app/controllers/hints_controller.rb
class HintsController < ApplicationController

  	# [View hints and tips-Story 4.22]
	# It fetches from database all the previous hints.
	# Parameters: 
	#	@hints: previous hints that had been entered before related to the model answer.
	# Returns: none
	# Author: Nadine Adel + Ahmed Osam
	def index
		session[:model_answer_id] = params[:model_answer_id]
		@model_answer = ModelAnswer.find_by_id(session[:model_answer_id])
		@hints = Hint.get_hints @model_answer.id
	end

	# [Edit helping hints - Story 4.13 ]
	# This action creates the form and retrives the data of the selected problem 
	#	to be being edited
	# Parameters:
	#	hint_id: id of the hint. 
	# Returns: none
	# Author: Mimi
	def edit
		session[:hint_id] = params[:hint_id]
		@hint = Hint.find_by_id(params[:hint_id])
	end	

	# [Edit helping hints - Story 4.13 ]
	# This action takes the passed parameters from 
	#	the creation form, edits a Hint record
	#	which assigned  to the respective problem. If the 
	#	edit fails the user is redirected to the form
	#	with a "Failed" message.
	# Parameters:
	#	hint_params[]: A list that has all fields entered by the user to in the
	#		edit_hint form
	# Returns: 
	#	flash[:notice]: A message indicating the success or failure of the edit
	# Author: Mimi
	def update
		@hint = Hint.find(session[:hint_id])
		if hint_params_edit[:message] != @hint.message ||
			hint_params_edit[:submission_counter] != @hint.submission_counter
			if @hint.message != hint_params_edit[:message]
				flash.keep[:notice] = "Content has changed"
			elsif @hint.submission_counter != hint_params_edit[:submission_counter]
				flash.keep[:notice] = "Submission Counter has changed"
			end
			begin
				if @hint.update_attributes(hint_params_edit)
					respond_to do |format|
						format.js
						format.html {redirect_to :action => "edit", :format => :js,
							:hint_id => @hint.id, :track_id => session[:track_id]}
					end
				else
					@hint = Hint.find_by_id(params[:hint_id])
					respond_to do |format|
						format.js
						format.html {redirect_to :action => "edit", :format => :js,
							:hint_id => @test_case.id, :track_id => session[:track_id]}
					end
				end
			rescue
				@hint = Hint.find_by_id(session[:hint_id])
				respond_to do |format|
					format.js
					format.html {redirect_to :action => "edit", :format => :js,
						:hint_id => @test_case.id, :track_id => session[:track_id]}
				end
			end
		end
	end

	# [Add hint - Story 4.10]
	# Allows Lecturer/TA to create a hint to help the student_users while solving a problem
	# Parameters: none
	# Returns:
	#	@hint: a new created hint to specific answer
	# Author: Ahmed Osam
	def new
		if params[:flag] == "1" 
			session[:flag] = params[:flag]
		elsif params[:flag] == "0"
			session[:flag] = params[:flag]
		end
		@hint = Hint.new
		session[:track_id] = params[:track_id]
		if(@hint == nil)
			session[:model_answer_id] = params[:model_answer_id]
			@model_answer = ModelAnswer.find_by_id(session[:model_answer_id])
		end
	end

	# [Add hint - Story 4.10]
	# Allows Lecturer/TA to create a hint to help the student_users while solving a problem
	# Parameters: 
	#	message: is the content of the hint
	#	time: is a countdown timer that hint will appear after it ends
	#	model_answer_id: is the id of the answer the hint related to
	# Returns:
	#	@hint: a new created hint to specific answer
	# Author: Ahmed Osam
	def create
		@hint = Hint.new
		@model_answer = ModelAnswer.find_by_id(session[:model_answer_id])
		@hint.message = hint_params[:message]
		@hint.time = 0
		@hint.category = false
		@hint.model_answer_id = session[:model_answer_id]
		@hint.submission_counter = hint_params[:submission_counter]
		if lecturer_signed_in?
			@hint.owner_type = "lecturer"
			@hint.owner_id = current_lecturer.id
		elsif teaching_assistant_signed_in?
			@hint.owner_type = "teaching assistant"
			@hint.owner_id = current_teaching_assistant.id
		end
		if @hint.save
			if session[:flag] == "1"
				redirect_to :controller => 'hints', :action => 'index', 
					:problem_id => session[:problem_id], :track_id => session[:track_id],
					:model_answer_id => session[:model_answer_id]
			elsif session[:flag] == "0"
				redirect_to :controller => 'hints', :action => 'new', 
					:problem_id => session[:problem_id], :track_id => session[:track_id],
					:model_answer_id => params[:model_answer_id],:flag => session[:flag]
			end
		else
			render :action=>'new', :locals => { :model_answer_id => @hint.model_answer_id,
				:flag => session[:flag],
				:track_id => session[:track_id], :problem_id => params[:problem_id]}
		end
	end

	# [Remove hint - Story 4.12]
	# Finds the hint that wanted to be removed
	# Parameters:
	#	id: id of the hint required to be removed
	# Returns:
	#	@hint: hint which will be removed
	# Author: Ahmed Osam
	def destroy
		@hint = Hint.find_by_id(params[:id])
		@hint.destroy
		redirect_to :controller => 'hints', :action => 'index', :problem_id => params[:problem_id],
			:track_id => params[:track_id], :model_answer_id => params[:model_answer_id]
	end

	# [Edit helping hints - Story 4.13 ]
	# Description: 
	#	take the parameters from the from
	# Parameters: none
	# Returns:
	#	Hash of paramas 
	# Author: Mimi
	private
		def hint_params
			params.require(:hint).permit(:message, :submission_counter, :id)
		end

	# [Add/Edit wizard - Story 1.28 ]
	# Description:
	#	take the parameters from the from
	# Parameters: none
	# Returns:
	#	Hash of paramas
	# Author: Ahmed Osam
		def hint_params_edit
			params.require(:hint_edit).permit(:message, :submission_counter)
		end

end

app/helpers/hints_helper.rb
module HintsHelper
end

app/views/hints/_form.html.erb
<% if lecturer_signed_in? || teaching_assistant_signed_in? %>
	<% if @hint.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@hint.errors.count, "error") %>
				prohibited the hint from being saved:
			</h2>
		</div>
		<ul>
			<% @hint.errors.full_messages.each do |msg| %>
				<li>
					<%= msg %>
				</li>
			<% end %>
		</ul>
	<% end %>
	<div id = "div_hint">
		<%= form_for :hint_edit, url: hint_path(@hint), method: :patch,
			remote: true do |hint_edit| %>
			<p>
				<h3><%= hint_edit.label :Content %></h3>
				<h4 align ="left"><%= @hint.message %></h4>
				<%= hint_edit.text_area :message, class:"form-control",
					style: "width:650px; height:250px;", :value => @hint.message %>
			</p>
			<p>
				<h3><%= hint_edit.label :Submission_Counter %></h3>
				<h4 align ="left"><%= @hint.submission_counter %></h4>
				<%= hint_edit.text_field :submission_counter, class:"form-control",
					style: "width:65px; height:40px;", :value => @hint.submission_counter %>
			</p>
			<%= hint_edit.submit "Save changes", class: "btn btn-large btn-info",
				style: "float: left" %>
		<% end %>
	</div>
<% end %>

app/views/hints/_hint_form.html.erb
<div id="div1">
	<% if flash[:notice] %>
		<div class= "alert alert-success"><%= flash[:notice] %></div>
	<% end %>
</div>
<%= form_for :hint_edit, url: hint_path(@hint), method: :patch, remote: true do |hint_edit| %>
	<p>
		<h3><%= hint_edit.label :Content %></h3>
		<h4 align ="left"><%= @hint.message %></h4>
		<%= hint_edit.text_area :message, class:"form-control",
			style:"width:650px; height:250px;", :value => @hint.message %>
	</p>
	<p>
		<h3><%= hint_edit.label :Submission_Counter %></h3>
		<h4 align ="left"><%= @hint.submission_counter %></h4>
		<%= hint_edit.text_field :submission_counter,
			class:"form-control", style:"width:65px;
			height:40px;", :value => @hint.submission_counter %>
	</p>
		<%= hint_edit.submit "Save changes",
			class: "btn btn-large btn-info", style: "float:left" %>
<% end %>

app/views/hints/edit.html.erb
<div class="left-row">
	<div class="container" style='width:100%;'>
		<div id = "crumbs">
			<ul>
				<li class = "sub"><a class = "preventclick">Problem</a></li>
				<li class = "sub1">
					<a class = "preventclick" style = "padding: 5px 15% 0 0px;">
						Test cases
					</a>
				</li>
				<li class = "sub2">
					<%= link_to "Model Answers", {:controller => 'model_answers', :action => 'edit',
						:problem_id => params[:problem_id],:track_id => params[:track_id],
						:model_answer_id => params[:model_answer_id]},{:method => :get,
						:style=>'padding: 5px 3.75% 0 0px;', :class => "css_class"} %>
				</li>
				<li class="sub3"><%= link_to "Tips", {:controller => 'tips', :action => 'index',
					:model_answer_id => session[:model_answer_id],
					:track_id => params[:track_id], :problem_id => session[:problem_id]},
					:method => :get %>
				</li>
				<li class = "sub4"><a class="visit" >Hints</a></li>
			</ul>
		</div><br><br><br>
		<h2>Edit Hint</h2>
		<%= render 'form' %>
		<div>
			<ul class = "navbar-brand pull-right">
				<%= link_to "Back", {:controller => 'tips', :action => 'index',
					:track_id => session[:track_id], :problem_id => session[:problem_id],
					:model_answer_id => session[:model_answer_id]},:method => :get,
					:class => "btn btn-info"%>
			</ul>
		</div>
	</div>
</div>

app/views/hints/index.html.erb
<div class="left-row">
	<div class="container" style='width:100%;'>
		<div id = "crumbs">
			<ul>
				<li class="sub"><a class="preventclick">Problem</a></li>
				<li class = "sub1"><a class="preventclick" style="padding: 5px 15% 0 0px;">Test Cases</a> </li>
				<li class="sub2"><%= link_to "Model Answers", {:controller => 'model_answers', :action => 'edit',
					:problem_id => params[:problem_id],:track_id => params[:track_id], 
					:model_answer_id => params[:model_answer_id]},{:method => :get, :style=>'padding: 5px 3.75% 0 0px;',
					:class => "css_class"} %></li>
				<li class="sub3"><%= link_to "Tips", {:controller => 'tips', :action => 'index',:model_answer_id => session[:model_answer_id],
					:track_id => params[:track_id], :problem_id => session[:problem_id]}, :method => :get %>
				</li>
				<li class = "sub4"><a class="visit" >Hints</a></li> 
			</ul>
		</div>
		<br><br>
		<div id="div1">
			<% if flash[:notice] %>
				<div class= "alert alert-success"><%= flash[:notice] %></div>
			<% end %>
		</div>
		<br><ul class = "navbar-brand pull-right"><%= link_to "Create Hint",
			{ :controller => 'hints', :action => 'new', :model_answer_id => params[:model_answer_id] ,:flag => 1, :problem_id => session[:problem_id], :track_id => session[:track_id], :flag => 1 },
			{ class: 'btn btn-info' } %></ul><br><br>
		<a href="#" return:false; class="Lst" onclick="toggle_visibility('foo3'); return false;"
			style="font:120px"> Previous Hints</a>
		<div id="foo3">
			<% if !@hints.any? %>
				<p>No previous Hints</p>
			<% end %>
			<% if !@hints.empty? %>
				<table class="table table-striped" style = "width:60%">
					<thead>
						<tr>
							<th style = "width:30%">Hints</th>
							<th style = "width:10%">Time of showing in seconds</th>
							<th style = "width:20%">Edit</th>
						</tr>
					</thead>
					<tbody>
						<% @hints.each do |hint1| %>
							<tr>
								<% if hint1.category == false %>
									<td style = "max-width: 300px; word-wrap:break-word;">
										<%= hint1.message %></td>
									<td style ="width:20%"><%= hint1.submission_counter %></td>
									<td>
										<%= link_to "Edit", {:action => 'edit',
											:controller => 'hints',:hint_id => hint1.id,
											:problem_id => params[:problem_id],
											:model_answer_id => params[:model_answer_id],
											:track_id => params[:track_id] },
											{class: 'btn btn-primary btn-xs', style: "text-decoration: none;"} %>
									</td>
									<td>
										<%= link_to "Delete Hint", { :controller => 'hints',
											:action => "destroy",:id => hint1.id,
											:problem_id => params[:problem_id],
											:model_answer_id => params[:model_answer_id],
											:track_id => session[:track_id] },
											data: { confirm: "Are you sure you want to delete this Hint?"},
											class: "btn btn-danger btn-xs", style: "float:left; text-decoration: none;",
											method: :delete %>
									</td>
								</tr>
							<% end %>
						<% end %>
					</tbody>
				</table>
			<% end %>
		</div>
		<div><ul class = "navbar-brand pull-right">
				<%= link_to "Back", {:controller => 'model_answers', :action => 'index',
							:track_id => session[:track_id], :problem_id => session[:problem_id], :model_answer_id =>session[:model_answer_id]},:method => :get,:class => "btn btn-info"%></ul>
		</div>
	</div>
</div>

app/views/hints/new.html.erb
<div class="left-row">
	<div class="container" style='width:100%;'>
		<% if (lecturer_signed_in? || teaching_assistant_signed_in?) &&
			session[:model_answer_id] != nil %>
			<div id = "crumbs">
				<ul>
					<li class = "sub"><a class = "preventclick">Problem</a></li>
					<li class = "sub1"><a class = "preventclick" style="padding:5px 15% 0 0px;">Test
					Cases</a></li>
					<li class="sub2"><a class = "preventclick" style="padding: 5px 3.75% 0 0px;">Model
					Answers</a> </li>
					<li class = "sub3"><a class = "preventclick" >Tips</a></li>
					<li class = "sub4"><a class = "visit" >hints</a> </li>
				</ul>
			</div><br><br>
			<h2>Create Hint for Model Answer
				<h1 style="color:red;">
					<%= ModelAnswer.find_by_id(session[:model_answer_id]).title %>
				</h1>
			</h2>
			<% if @hint.errors.any? %>
				<div id = "error_explanation">
					<h2>
						<%= pluralize(@hint.errors.count, "error") %>
						prohibited the Hint from being saved:
					</h2>
				</div>
				<ul>
					<% @hint.errors.full_messages.each do |msg| %>
						<li>
							<%= msg %>
						</li>
					<% end %>
				</ul>
			<% end %>
			<div id = "div_hint" style = "float:center;">
				<%= form_for :hint, url: hints_path do |t| %>
					<p>
						<%= t.label :Content %><br>
						<%= t.text_area :message, class:"form-control", style:"width:350px",
							:value => @hint.message %>
					</p>
					<p>
						<%= t.label :Submission_counter %><br>
						<%= t.text_field :submission_counter, class:"form-control", style: "width:55px;
						height:35px;", :value => @hint.submission_counter %>
					</p>
					<p>
						<%= t.hidden_field :model_answer_id, value: params[:model_answer_id] %>
					</p>
					<p style = "position: relative; bottom: 30%; left: 0%;">
						<%= t.submit class: 'btn btn-info' %>
					</p>
				<% end %>
			</div>
			<div>
				<ul class = "navbar-brand pull-right">
					<%= link_to "Done", {:controller => 'tracks', :action => 'show',
						:id => session[:track_id]},:method => :get,:class => "btn btn-info"%>
				</ul>
			</div>

		<% end %>
	</div>
</div>

app/views/hints/update.js.erb
$('#div_hint').html("<%= escape_javascript(render 'hints/hint_form') %>");