config/routes.rb
Tutor::Application.routes.draw do
	
	ActiveAdmin.routes(self)
	devise_for :admin_users, ActiveAdmin::Devise.config
	devise_for :teaching_assistants
	devise_for :students
	devise_for :lecturers

	get 'courses/sign_up'
	get 'courses/find_course/:id' => 'courses#find_course'
	get 'tracks/show_classmates/:id' => 'tracks#show_classmates'
	get 'solutions/mark_solution'
	get 'solutions/view_submissions'
	post 'solutions/compile_solution' => 'solutions#compile_solution'
	post 'courses/new' => 'courses#new'
	post 'courses/share' => 'courses#share'
	post 'solutions/execute' => 'solutions#execute'
	post '/posts/:id' => 'posts#update'
	post 'tracks/insert_recommendation' => 'tracks#insert_recommendation'
	post 'debuggers/:id' => 'debuggers#start'
	post 'cproblems/submit' => 'cproblems#submit'
	get 'contests/add_problems/:id' => 'contests#add_problems'
	get 'contests/:id/standings' => 'contests#standings'
	get 'contests/:id/registrants' => 'contests#registrants'
	get 'contests/:id/register' => 'contests#register'
	post 'contests/add/:id' => 'contests#add'
	get 'problems/edit'
	get '/courses/return_list' => 'courses#return_list'
	get 'c_problems/new'
	post 'c_problems/create'
	post '/courses/register' => 'courses#register'

	get "tips/new"
	get "tips/create"
	get "tips/show"
	get "tips/index"
	get "tips/edit"
	get "tips/destroy"
	post "tips/:id/edit" => 'tips#update'
	get "problems/destroy"
	get "test_cases/edit"
	get "test_cases/destroy"
	get "model_answers/edit"
	get "hints/edit"
	get "model_answers/destroy"
	get "model_answers/back"
	get "notes/destroy"
	get "grades/view_grades"

	root 'site#index'
	resources :tracks do
		post 'getProblems', on: :member
	end
	resources :assignment_testcases
	resources :problems_by_tas
	resources :solutions
	resources :problems
	resources :courses
	resources :cproblems
	resources :contests
	resources :contributors

	post "courses/choose"
	post "courses/existing"
	post "courses/duplicate"
	get "model_answers/new"
	post "model_answers/new"

	resources :model_answers

	resources :discussion_boards do
		post 'toggle', on: :member
	end
	post 'courses/new' => 'courses#new'
	resources :courses do
		post 'topics/new' => 'topics#new'
		resources :topics
	end
	resources :model_answers do
		post "model_answers/new"
	end

	resources :assignments do
		get "assignments/new"
		post "assignments/show"
		get "assignments/show"
	end
	resources :assignments_problems do
		get "assignment_problems/new"
		get "assignment_problems/edit"
		get "assignment_problems/show"
		get "assignment_problems/index"
		post "assignment_problems/update"
		post "assignment_problems/show"
	end
	post "/assignment_problems/complete"
	resources :assignments_testcases do
		get "assignment_testcases/new"
		get "assignment_testcases/show"
		get "assignment_testcases/index"
		get "assignment_testcases/edit"
		get "/assignment_testcases/new"
	end

	resources :courses do
		post 'hide', on: :member
	end
	resources :test_cases

	resources :courses
	resources :test_cases
	resources :model_answers
	resources :solutions
	resources :topics
	resources :replies
	resources :hints
	resources :lecturers
	resources :teaching_assistants
	resources :students
	resources :posts
	resources :facebook
	resources :tips
	resources :notifications
	resources :contests
	resources :assignments
	resources :assignment_problems
	resources :notes
	resources :grades

	resources :tracks do
		member do
			get 'getProblems'
		end
	end

	resources :courses do
		member do
			get 'show_grades'
		end
	end

	resources :assignments do
		member do
			get 'show_correction'
		end
	end

	resources :courses do
		collection do
			post 'sort'
		end
	end

	resources :topics do
		collection do           
			post 'sort'
		end
	end

	resources :discussion_boards do
		member do
			post 'toggle'
		end
	end
	
	resources :model_answers do
		post "model_answers/new"
	end

	resources :tips do
		 get "tips/index"
	end

	resources :hints do
		 get "hints/index"
	end

	resources :solutions_constraints do
		collection do
			post "new"
		end
	end

	resources :problems do
		get 'done'
		get 'destroy_problem'
	end

	resources :courses do
		post 'topics/new' => 'topics#new'
		resources :topics
		resources :teaching_assistants
		post 'teaching_assistants/new' => 'teaching_assistants#new'
		resources :acknowledgements
		resources :resources, only: [:create, :index, :new, :destroy] do
			get :add_more, on: :collection
		end
	end

	get "utilities/simple_search"
	get "utilities/advanced_search"
	get "utilities/auto_complete"

    match ":controller(/:action(/:id))", :via => :get
end

app/views/resources/_resource_fields.html.erb
<div class="resource">
	<%= f.label :link %>
	<%= f.url_field :link , autofocus: true, class:"form-control",
		style: "width:300px", placeholder: "Link" %>
	<%= link_to_remove_association "remove resource", f, {wrapper_class: 'resource'} %>
</div>

app/views/resources/index.html.erb
<div class= "left-box" >
	<div class="xob">
		<div class = "course_info panel-body" >
			<div class= "row course_title">
				<div class="course_code"><%= @course.code %></div>
				<div class="course_name"><%= @course.name %> | Resources</div>
			</div>
			<div class="row">
				<div class="course_sem">
					Semester <%= @course.semester %>
					Class <%= @course.year %>
				</div>
			</div>
		</div>
			<% unless flash[:notice].nil? %>
				<div class= "alert alert-danger">
					<%= flash[:notice] %>
					<%- flash[:notice] = nil %>
				</div>
			<% end %>
			<div>
				<%- unless @course.resources.empty? %>
					<%- @course.resources.each do |resource| %>
						<div class="media">
							<a class="pull-left" href="<%= resource.link %>">
								<img class="media-object" src="<%= resource.img %>"\
									height="64" width="64" alt="...">
							</a>
							<div class="media-body">
								<h4 class="media-heading">
									<a href="<%= resource.link %>"><%= resource.link %></a>
								</h4>
								<%= resource.description %>
							</div>
						</div>
					<% end%>
				<% else %>
					<div class="panel panel-default">
						<div class="panel-body" align="center">
							<h3>No Resources</h3>
						</div>
					</div>
				<% end %>
			</div>
			<%- if lecturer_signed_in? %>
				<%= link_to "Add Resources", new_course_resource_path(@course),
				class: "btn btn-success",
					 method: :get %>
			<% end %>
		</div>
	</div>

app/views/resources/new.html.erb
<%= javascript_include_tag "resources" %>

<div class="container well" style="width:100% !important; background-color:#fff !important; border-radius: 5px;">
	<%= form_for @course, url: { controller: "resources", action: "create"}, method: :post do |f| %>
		<div id="resources" class="resources">
			<%= link_to_add_association "Add More Resources", f, :resources,\
				"data-association-insertion-method" => "append",\
				class: "pull-right btn btn-primary" %>
			<div>
				<%= f.fields_for :resources do |resource| %>
					<%= render "resource_fields" , f: resource %>
				<% end %>
			</div>
		</div>
		<br/>
		<p>
			<%= f.submit "Save", class: "btn btn-success"%>
		</p>
	<% end %>
</div>