config/routes.rb
Tutor::Application.routes.draw do
	
	ActiveAdmin.routes(self)
	devise_for :admin_users, ActiveAdmin::Devise.config
	devise_for :teaching_assistants
	devise_for :students
	devise_for :lecturers

	get 'courses/sign_up'
	get 'courses/find_course/:id' => 'courses#find_course'
	get 'tracks/show_classmates/:id' => 'tracks#show_classmates'
	get 'solutions/mark_solution'
	get 'solutions/view_submissions'
	post 'solutions/compile_solution' => 'solutions#compile_solution'
	post 'courses/new' => 'courses#new'
	post 'courses/share' => 'courses#share'
	post 'solutions/execute' => 'solutions#execute'
	post '/posts/:id' => 'posts#update'
	post 'tracks/insert_recommendation' => 'tracks#insert_recommendation'
	post 'debuggers/:id' => 'debuggers#start'
	post 'cproblems/submit' => 'cproblems#submit'
	get 'contests/add_problems/:id' => 'contests#add_problems'
	get 'contests/:id/standings' => 'contests#standings'
	get 'contests/:id/registrants' => 'contests#registrants'
	get 'contests/:id/register' => 'contests#register'
	post 'contests/add/:id' => 'contests#add'
	get 'problems/edit'
	get '/courses/return_list' => 'courses#return_list'
	get 'c_problems/new'
	post 'c_problems/create'
	post '/courses/register' => 'courses#register'

	get "tips/new"
	get "tips/create"
	get "tips/show"
	get "tips/index"
	get "tips/edit"
	get "tips/destroy"
	post "tips/:id/edit" => 'tips#update'
	get "problems/destroy"
	get "test_cases/edit"
	get "test_cases/destroy"
	get "model_answers/edit"
	get "hints/edit"
	get "model_answers/destroy"
	get "model_answers/back"
	get "notes/destroy"
	get "grades/view_grades"

	root 'site#index'
	resources :tracks do
		post 'getProblems', on: :member
	end
	resources :assignment_testcases
	resources :problems_by_tas
	resources :solutions
	resources :problems
	resources :courses
	resources :cproblems
	resources :contests
	resources :contributors

	post "courses/choose"
	post "courses/existing"
	post "courses/duplicate"
	get "model_answers/new"
	post "model_answers/new"

	resources :model_answers

	resources :discussion_boards do
		post 'toggle', on: :member
	end
	post 'courses/new' => 'courses#new'
	resources :courses do
		post 'topics/new' => 'topics#new'
		resources :topics
	end
	resources :model_answers do
		post "model_answers/new"
	end

	resources :assignments do
		get "assignments/new"
		post "assignments/show"
		get "assignments/show"
	end
	resources :assignments_problems do
		get "assignment_problems/new"
		get "assignment_problems/edit"
		get "assignment_problems/show"
		get "assignment_problems/index"
		post "assignment_problems/update"
		post "assignment_problems/show"
	end
	post "/assignment_problems/complete"
	resources :assignments_testcases do
		get "assignment_testcases/new"
		get "assignment_testcases/show"
		get "assignment_testcases/index"
		get "assignment_testcases/edit"
		get "/assignment_testcases/new"
	end

	resources :courses do
		post 'hide', on: :member
	end
	resources :test_cases

	resources :courses
	resources :test_cases
	resources :model_answers
	resources :solutions
	resources :topics
	resources :replies
	resources :hints
	resources :lecturers
	resources :teaching_assistants
	resources :students
	resources :posts
	resources :facebook
	resources :tips
	resources :notifications
	resources :contests
	resources :assignments
	resources :assignment_problems
	resources :notes
	resources :grades

	resources :tracks do
		member do
			get 'getProblems'
		end
	end

	resources :courses do
		member do
			get 'show_grades'
		end
	end

	resources :assignments do
		member do
			get 'show_correction'
		end
	end

	resources :courses do
		collection do
			post 'sort'
		end
	end

	resources :topics do
		collection do           
			post 'sort'
		end
	end

	resources :discussion_boards do
		member do
			post 'toggle'
		end
	end
	
	resources :model_answers do
		post "model_answers/new"
	end

	resources :tips do
		 get "tips/index"
	end

	resources :hints do
		 get "hints/index"
	end

	resources :solutions_constraints do
		collection do
			post "new"
		end
	end

	resources :problems do
		get 'done'
		get 'destroy_problem'
	end

	resources :courses do
		post 'topics/new' => 'topics#new'
		resources :topics
		resources :teaching_assistants
		post 'teaching_assistants/new' => 'teaching_assistants#new'
		resources :acknowledgements
		resources :resources, only: [:create, :index, :new, :destroy] do
			get :add_more, on: :collection
		end
	end

	get "utilities/simple_search"
	get "utilities/advanced_search"
	get "utilities/auto_complete"

    match ":controller(/:action(/:id))", :via => :get
end

app/controllers/test_cases_controller.rb
class TestCasesController < ApplicationController

	# [Add test case-story 4.8]
	# Shows all the test cases.
	# Parameters:
	#	track_id: track id containing problems.
	#	problem_id: problem_id.
	# Returns:
	#	List of all the test cases related to a certain problem.
	# Author: Lin + Ahmed Osam
	def index
		session[:track_id] = params[:track_id]
		session[:problem_id] = params[:problem_id]
		@problem = Problem.find_by_id(session[:problem_id])
		@test_cases = @problem.test_cases
	end

	# [Add test case-story 4.8]
	# Display the form that is used to add a test case.
	# Parameters:
	#	track_id: track id containing problems.
	#	problem_id: problem id test case related to.
	#	flag: to identify wether redirect to new or index page.
	# Returns: none
	# Author: Lin + Ahmed Osam
	def new
		session[:track_id] = params[:track_id]
		session[:problem_id] = params[:problem_id]
		if params[:flag] == "1" 
			session[:flag] = params[:flag]
		elsif params[:flag] == "0"
			session[:flag] = params[:flag]
		end
		@problem = Problem.find(session[:problem_id])
		@test_case = TestCase.new
	end

	# [Add test case-story 4.8]
	# Saves the new test case into the database.(What the form the 'new' method will submit to)
	# Parameters:
	#	problem_id: problem id test case related to.
	#	track_id: track id containing problems
	#	flag: to identify wether redirect to new or index page.
	# Returns:
	#	In case of success a flash notice will appear:"Post created successfully"
	#	In case of failure a flash notice will appear:"Can't add test case!"
	# Author: Lin
	def create
		@problem = Problem.find_by_id(session[:problem_id])
		@test_case = TestCase.new
		if lecturer_signed_in?
			@test_case = TestCase.new(post_params)
			@test_case.owner_id = current_lecturer.id
			@test_case.owner_type = "lecturer"
			@test_case.problem_id = session[:problem_id]
		elsif teaching_assistant_signed_in?
			@test_case = TestCase.new(post_params)
			@test_case.owner_id = current_teaching_assistant.id
			@test_case.owner_type = "teaching assistant"
			@test_case.problem_id = session[:problem_id]
		end
		if @test_case.save
			@problem.test_cases << @test_case
			if session[:flag] == "1"
				redirect_to :controller => 'test_cases', :action => 'index',
					:problem_id => session[:problem_id], :track_id => session[:track_id], :flag => "1"
			elsif session[:flag] == "0"
				redirect_to :controller => 'model_answers', :action => 'new',
					:problem_id => session[:problem_id], :track_id => session[:track_id], :flag => "0"
			end
		else
			render :action=>'new', :problem_id => @test_case.problem_id, :flag => session[:flag]
		end
	end

	# [Edit test case-story 4.9]
	# Edit test case
	# Parameters:
	#	@test_case:Test case to be edited.
	#	track_id: track id containing problems.
	#	problem_id: problem id test case related to.
	#	test_case_id: test case id.
	#	flag: to identify wether redirect to new or index page.
	# Returns: none
	# Author: Nadine Adel + Ahmed Osam
	def edit
		session[:problem_id] = params[:problem_id]
		session[:track_id] = params[:track_id]
		session[:test_case_id] = params[:test_case_id]
		@test_case = TestCase.find_by_id(session[:test_case_id])
	end

	# [Edit test case-story 4.9]
	# Update test case in the database
	# Parameters:
	#	@test_case: Test case to be updated.
	#	input: input required for test case.
	#	output: output required for test case.
	# Returns:
	#	Flash message if the test case is updated or not
	# Author: Nadine Adel + Ahmed Osam
	def update
		@test_case = TestCase.find(session[:test_case_id])
		if test_case_params[:input] != @test_case.input ||
			test_case_params[:output] != @test_case.output
			if @test_case.input != test_case_params[:input]
				flash.keep[:notice] = "Input has changed"
			elsif @test_case.output != test_case_params[:output]
				flash.keep[:notice] = "Output has changed"
			end
			begin
				if @test_case.update_attributes(test_case_params)
					respond_to do |format|
						format.js
						format.html {redirect_to :action => "edit", :format => :js,
							:test_case_id => @test_case.id, :track_id => session[:track_id]}
					end
				else
					@test_case = TestCase.find_by_id(params[:test_case_id])
					respond_to do |format|
						format.js
						format.html {redirect_to :action => "edit", :format => :js,
							:test_case_id => @test_case.id, :track_id => session[:track_id]}
					end
				end
			rescue
				@test_case = TestCase.find_by_id(session[:test_case_id])
				respond_to do |format|
					format.js
					format.html {redirect_to :action => "edit", :format => :js,
						:test_case_id => @test_case.id, :track_id => session[:track_id]}
				end
			end
		end
	end

	# [Remove Test Case - Story 4.16]
	# This action takes the test case id, and check if it is not the last test case in the problem 
	#	and removes it from the database and then redirects the user to the edit problem page of 
	#	the problem that had the test case with a "Test case successfully Deleted" message.
	# Parameters:
	#	params[:test_case_id]: The current test case's id
	# Returns: 
	#	flash[:notice]: A message indicating the success of the deletion
	# Author: Ahmed Atef + Ahmed Osam
	def destroy
		@test_case = TestCase.find_by_id(params[:test_case_id])
		@current = Problem.find_by_id(@test_case.problem_id)
		if @current.test_cases.count == 1
			flash[:notice] = "Cannot delete problem's last test case"
			redirect_to :back and return
		elsif @test_case.destroy
			flash[:notice] = "Test case successfully Deleted"
			redirect_to(:controller => 'test_cases', :action => 'index', :problem_id => @current.id,
				:track_id => session[:track_id])
		end
	end

	# [Add test case-story 4.8]
	# Private method. Controls the test case parameters that can be accessed.
	# Parameters: none
	# Returns: none
	# Author: Lin + Ahmed Osam
	private
	def post_params
		params.require(:test_case).permit(:input, :output, :problem_id)
	end

	# [Add/Edit wizard - Story 1.28 ]
	# Description:
	#	take the parameters from the from
	# Parameters: none
	# Returns:
	#	Hash of paramas
	# Author: Ahmed Osam
		def test_case_params
			params.require(:test_case).permit(:input, :output, :problem_id)
		end

end

app/views/test_cases/_form.html.erb
<%-#Lin: This is a form where the TA can add a test case.It has 2 labels and 2 textfields -%>
<%= form_for :test_case , url: test_cases_path do |f| %>
	<p>
		<p> 
			<span class="glyphicon glyphicon-info-sign"></span>
			Please insert values in input and output fields each in an new line if more than one.
		</p>
		<%= f.label :Input %>
		<%= f.text_area :input, style: "width:450px; height:200px;" %><br>
 		<%= f.label :Output %>
		<%= f.text_area :output, style: "width:450px; height:200px;" %><br>
		<%= f.hidden_field :problem_id, value: params[:problem_id] %>
	</p>
	<p>
		<%= f.submit 'Add Test Case' %>
	</p>
<% end %>

app/views/test_cases/_form2.html.erb
<div id="div1">
	<% if flash[:notice] %>
		<div class= "alert alert-success"><%= flash[:notice] %></div>
	<% end %>
</div>
<%= form_for :test_case, url: test_case_path(@test_case), method: :patch, remote: true do |test_case| %>
	<h2>Test Case </h2>
	<p>
		<span class="glyphicon glyphicon-info-sign"></span>
		Please insert values in input and output fields each in an new line if more than one.
	</p>
	<h3><%= test_case.label :Input%> </h3>
	<h4 align ="left"><%= @test_case.input %></h4>
	<%= test_case.text_area :input, class:"form-control",
		style: "width:450px; height:200px;" %><br>
	<h3><%= test_case.label :Output %></h3>
	<h4 align ="left"><%= @test_case.output %></h4>
	<%= test_case.text_area :output, class:"form-control",
		style: "width:450px; height:200px;" %><br>
	<br><%= test_case.submit "Save changes", class: "btn btn-large btn-info" %><br>
<% end %>

app/views/test_cases/edit.html.erb
<div class="left-row">
	<div class="container" style='width:100%;'>
		<div id = "crumbs">
			<ul>
				<li class = "sub"><a class = "preventclick">Problem</a></li>
				<li class = "sub1">
					<a class = "visit" style = "padding: 5px 15% 0 0px;">
						Test Cases
					</a>
				</li>
				<li class = "sub2">
					<a class = "preventclick" style = "padding: 5px 3.75% 0 0px;">
						Model Answers
					</a>
				</li>
				<li class = "sub3"><a class = "preventclick" >Tips</a> </li>
				<li class = "sub4"><a class = "preventclick">Hints</a> </li>
			</ul>
		</div><br><br>

		<% provide(:title, "Edit Test Case") %>
		<% if @test_case.errors.any? %>
			<div id = "error_explanation">
				<h2><%= pluralize(@test_case.errors.count, "error") %>
					prohibited this course from being saved:
				</h2>
				<ul>
					<% @test_case.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<div id = "diva"><br><br>
			<%= form_for :test_case, url: test_case_path(@test_case), method: :patch,
				remote: true do |test_case| %>
				<h2>Test Case </h2>
				<h3><%= test_case.label :Input%> </h3>
				<h4 align = "left"><%= @test_case.input %></h4>
				<%= test_case.text_area :input, class:"form-control",
					style: "width:450px; height:200px;" %><br>
				<h3><%= test_case.label :Output %></h3>
				<h4 align = "left"><%= @test_case.output %></h4>
				<%= test_case.text_area :output, class:"form-control",
					style: "width:450px; height:200px;" %><br>
				<%= test_case.submit "Save changes", class: "btn btn-large btn-info" %><br>
			<% end %>
		</div>

		<div><ul class = "navbar-brand pull-right">
				<%= link_to "Back", {:controller => 'test_cases', :action => 'index',
					:track_id => session[:track_id], :problem_id => session[:problem_id],
					:model_answer_id => session[:model_answer_id]},:method => :get,:class => "btn btn-info"%></ul>
		</div>
	</div>
</div>

app/views/test_cases/index.html.erb
<div class="left-row">
	<div class="container" style='width:100%;'>
		<div id = "crumbs">
			<ul>
				<li class="sub"><%= link_to "Problem", {:controller => 'problems', :action => 'edit',
							:problem_id => session[:problem_id], :track_id => session[:track_id]},:method => :get %></li>
				<li class="sub1"><a class="visit" style ="padding: 5px 15% 0 0px;">Test Cases</a> </li>
						
				<li class="sub2"><%= link_to "Model Answers", {:controller => 'model_answers', :action => 'index',:problem_id => session[:problem_id], :track_id => session[:track_id]}, :style=>'padding: 5px 3.75% 0 0px;', :class => "css_class"%> </li>
				<li class="sub3"><a class = "preventclick" >Tips</a> </li>
				<li class="sub4"><a class = "preventclick">Hints</a> </li>
			</ul>
		</div><br><br><br>
		<div id="div1">
			<% if flash[:notice] %>
				<div class= "alert alert-danger"><%= flash[:notice] %></div>
			<% end %>
		</div>
		<ul class = "navbar-brand pull-right"><%= link_to "Create Test Case",
			{ :controller => 'test_cases', :action => 'new', :model_answer_id => params[:model_answer_id] ,:flag => 1, :problem_id => session[:problem_id], :track_id => session[:track_id] },
			{ class: 'btn btn-info' } %></ul><br><br>
		<a href="#" return:false; class= "Lst" onclick= "toggle_visibility('foo1');
				return false;" style="font:120px">Test Cases</a>
		<div id="foo1">
			<% if !@test_cases.any? %>
				<p>You have no previous test cases</p>
			<% end %>
			<% if !@test_cases.empty? %>
				<table class="table table-striped" style = "width:60%">
					<thead>
						<tr>
							<th style ="width:20%">Input</th>
							<th style ="width:20%">Output</th>
							<th style ="width:20%">Edit</th>
							<th style ="width:20%">Delete</th>
						</tr>
					</thead>
					<tbody>
						<% @test_cases.each do |test_case| %>
							<tr>
								<td><%= test_case.input %></td>
								<td><%= test_case.output %></td>
								<td><%= link_to " Edit", {:controller => 'test_cases',
									:action => 'edit', :method => :get, :test_case_id => test_case.id, :track_id => session[:track_id], :problem_id => session[:problem_id]},
										{class: 'btn btn-info btn-xs', style: "text-decoration:none"}%></td>
								<td><%= button_to "Delete Test Case", 
										{:controller => 'test_cases',:action => 'destroy',
										:test_case_id => test_case.id},method: :delete,
										class:'btn btn-danger btn-xs', :confirm => 
										"Are you sure you want to delete this test case ?" %>
								</td>
							</tr>
						<% end %>
					</tbody>				
				</table>
			<% end %>
		</div>
		<div><ul class = "navbar-brand pull-right"><%= link_to "Return to Track",
			{ :controller => 'tracks', :action => 'show', :model_answer_id => params[:model_answer_id] ,:flag => 1, :problem_id => session[:problem_id], :id => session[:track_id] },
			{ class: 'btn btn-info' } %></ul>

		</div>
	</div>
</div>

app/views/test_cases/new.html.erb
<div class="left-row">
	<div class="container" style='width:100%;'>
		<div id = "crumbs">
			<ul>
				<li class="sub"><a class = "preventclick">Problem</a></li>
				<li class="sub1"><a class="visit" style="padding: 5px 15% 0 0px;">Test Cases</a> </li>
				<li class="sub2">
					<a class="preventclick" style="padding: 5px 3.75% 0 0px;">
					Model Answers</a>
				</li>
				<li class="sub3"><a class="preventclick">Tips</a></li>
				<li class="sub4"><a class="preventclick">Hints</a></li>
			</ul>
		</div><br><br>
		<%= form_for :test_case , url: test_cases_path do |f| %>
			<% if @test_case.errors.any? %>
				<div id="error_explanation">
					<h2><%= pluralize(@test_case.errors.count, "error") %>
						prohibited this course from being saved:
					</h2>
					<ul>
						<% @test_case.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			<% else %>
				<%= f.hidden_field :problem_id, :value => @problem.id %>
			<% end %>
			<h1>
				Please insert Test Case for problem
				<h2 style="color:red;">
					<%= @problem.title %>
				</h2>
			</h1>
			<p>
				<p>
					<span class="glyphicon glyphicon-info-sign"></span>
					Please insert values in input and output fields each in
						an new line if more than one value in the same test case.
				</p>
				<%= f.label :Input %>
				<br><%= f.text_area :input, class: "form-control",
						style: "width:450px; height:200px;" %><br>
				<%= f.label :Output %>
				<br><%= f.text_area :output, class: "form-control",
						style: "width:450px; height:200px;" %>
				<%= f.hidden_field :problem_id, :value => session[:problem_id] %>
			</p>
			<p>
				<%= f.submit 'Add Test Case', type: "submit" ,value: "Add Test Case",
					onclick: "canleave()", class: "btn btn-large btn-info",
					:flag => params[:flag] %>
			</p>
		<% end %>
	</div>
</div>		
<script>
	// confirmBrowseAway is a funcction to prevent user from leaving the page without confirming that.
	// workIsDone Boolean variable.
	var workIsDone = false;
	window.onbeforeunload = confirmBrowseAway;
	function confirmBrowseAway()
	{
		if (!workIsDone) {
			return "Your problem will be saved as Incomplete! " +
			"\n You can create new test case any time " +
			" \n and it will be saved as complete if having at least 1 test case and 1 model answer.";
		}
	}
	function canleave()
	{
		//canleave is a function to let the user leave when called without any confirming boxes.
		// The user has finished their work, so we don't
		// need a warning anymore!
		workIsDone = true;
	}
</script>

app/views/test_cases/update.js.erb
$('#diva').html("<%= escape_javascript(render 'test_cases/form2') %>");